name: finance_management
description: FinCal - A modern finance management web app built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  http: ^1.1.0
  google_fonts: ^6.1.0
  supabase_flutter: ^2.5.6
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  image: ^4.1.3
  qr_flutter: ^4.1.0
  app_links: ^6.3.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/app_icon.png

# flutter_launcher_icons:
#   android: "launcher_icon"
#   image_path: "assets/app_icon.jpg"
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/app_icon.jpg"

